"""seed role

Revision ID: 
Revises: 
Create Date: 

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql.selectable import TableClause


# revision identifiers, used by Alembic.
revision = ''
down_revision = ''
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    seed_role(op)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(f"delete from role where code is not null;")
    # ### end Alembic commands ###


def to_camel(var: str):
    splitted_string = var.split('_')
    return ' '.join(word.capitalize() for word in splitted_string)


def seed_role(op: op):
    tb_role: TableClause = sa.table('role',
    sa.column('code', sa.String),
    sa.column('is_deleted', sa.Boolean)
    )

    insert_data = [
        {
            'code': 'super_admin'
        }
    ]

    op.bulk_insert(tb_role, insert_data)
